[GEMINI]
GEMINI_API_KEY = "AIzaSyDoQfk01n7VGoTf3f-W29ck1otORUKid-8"

[MONGO]
MONGO_URI = "mongodb+srv://nutrilink26:uMB2sctEmpWJU8ta@gophish0.nipe8.mongodb.net/?retryWrites=true&w=majority&appName=GoPhish0"